FROM wordpress:php7.4-fpm

ENV PHPREDIS_VERSION 5.3.0

RUN apt-get update -y && apt-get install zlib1g-dev libpng-dev libjpeg-dev \
 libicu-dev libxml2-dev libc6-dev libfreetype6-dev mariadb-client -y && apt-get autoremove -y

RUN docker-php-ext-configure gd --with-freetype --with-jpeg && \
    ocker-php-ext-configure intl && docker-php-ext-install dom

RUN mkdir -p /usr/src/php/ext/redis \
    && curl -L https://github.com/phpredis/phpredis/archive/$PHPREDIS_VERSION.tar.gz | tar xvz -C /usr/src/php/ext/redis --strip 1 \
    && echo 'redis' >> /usr/src/php-available-exts \
    && docker-php-ext-install redis

COPY --from=wordpress:cli-php7.4 /usr/local/bin/wp /usr/local/bin/wp